FROM golang:1.21

WORKDIR /fase-4-hf-payment/src/app

COPY . .

ENV GOPATH=/fase-4-hf-payment

RUN go build -ldflags "-w -s" -o bin/hermesfoods cmd/http/*.go

ENTRYPOINT ["./bin/hermesfoods"]

EXPOSE 8080
